<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <DefaultItemExcludes>$(DefaultItemExcludes);obj\**;bin\**</DefaultItemExcludes>
        <BaseOutputPath>$(MSBuildThisFileDirectory)bin\</BaseOutputPath>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    </PropertyGroup>

  <PropertyGroup>
    <TargetDotnetVersion>net8.0</TargetDotnetVersion>
    <Platforms>x64;ARM64</Platforms>
    <AvaloniaVersion>11.0.9</AvaloniaVersion>
    <CefGlueVersion>120.6099.211.1</CefGlueVersion>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <!-- Please see https://github.com/OutSystems/WebView?tab=readme-ov-file#versioning for versioning rules -->
    <Version>3.120.11</Version>
    <Authors>ImeSense,acidicMercury8</Authors>
    <Product>WebViewControl</Product>
    <Copyright>Copyright © OutSystems 2023</Copyright>
    <RepositoryUrl>https://github.com/imesense-packages/cefglue-webview</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)' == '' or '$(Platform)' == 'x64'">
    <PackageSuffix>.x64</PackageSuffix>
    <CefGluePackageSuffix>.x64</CefGluePackageSuffix>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)' == 'ARM64'">
    <PackageSuffix>.ARM64</PackageSuffix>
    <CefGluePackageSuffix>.ARM64</CefGluePackageSuffix>
  </PropertyGroup>
</Project>
