<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetDotnetVersion)</TargetFramework>
        <RootNamespace>TestResourceAssembly</RootNamespace>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU'">$(BaseOutputPath)$(Configuration)\$(TargetFramework)\$(RootNamespace)\$(AssemblyVersion)\</OutputPath>
        <OutputPath Condition="'$(Platform)' != '' and '$(Platform)' != 'AnyCPU'">$(BaseOutputPath)$(Platform)\$(Configuration)\$(TargetFramework)\$(RootNamespace)\$(AssemblyVersion)\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resource.txt" />
    </ItemGroup>
</Project>
